#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hayaaFinal
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="haya")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertاداة(اداة instance);
    partial void Updateاداة(اداة instance);
    partial void Deleteاداة(اداة instance);
    partial void Insertالاعادة(الاعادة instance);
    partial void Updateالاعادة(الاعادة instance);
    partial void Deleteالاعادة(الاعادة instance);
    partial void Insertالمستعير(المستعير instance);
    partial void Updateالمستعير(المستعير instance);
    partial void Deleteالمستعير(المستعير instance);
    partial void Insertالاستعارة(الاستعارة instance);
    partial void Updateالاستعارة(الاستعارة instance);
    partial void Deleteالاستعارة(الاستعارة instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::hayaaFinal.Properties.Settings.Default.hayaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<اداة> اداةs
		{
			get
			{
				return this.GetTable<اداة>();
			}
		}
		
		public System.Data.Linq.Table<الاعادة> الاعادةs
		{
			get
			{
				return this.GetTable<الاعادة>();
			}
		}
		
		public System.Data.Linq.Table<المستعير> المستعيرs
		{
			get
			{
				return this.GetTable<المستعير>();
			}
		}
		
		public System.Data.Linq.Table<الاستعارة> الاستعارةs
		{
			get
			{
				return this.GetTable<الاستعارة>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.اداة")]
	public partial class اداة : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _اسم_الاداة;
		
		private System.Nullable<int> _العدد;
		
		private string _رقم__الاداة;
		
		private EntitySet<الاعادة> _الاعادةs;
		
		private EntitySet<الاستعارة> _الاستعارةs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onاسم_الاداةChanging(string value);
    partial void Onاسم_الاداةChanged();
    partial void OnالعددChanging(System.Nullable<int> value);
    partial void OnالعددChanged();
    partial void Onرقم__الاداةChanging(string value);
    partial void Onرقم__الاداةChanged();
    #endregion
		
		public اداة()
		{
			this._الاعادةs = new EntitySet<الاعادة>(new Action<الاعادة>(this.attach_الاعادةs), new Action<الاعادة>(this.detach_الاعادةs));
			this._الاستعارةs = new EntitySet<الاستعارة>(new Action<الاستعارة>(this.attach_الاستعارةs), new Action<الاستعارة>(this.detach_الاستعارةs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_اسم_الاداة", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string اسم_الاداة
		{
			get
			{
				return this._اسم_الاداة;
			}
			set
			{
				if ((this._اسم_الاداة != value))
				{
					this.Onاسم_الاداةChanging(value);
					this.SendPropertyChanging();
					this._اسم_الاداة = value;
					this.SendPropertyChanged("اسم_الاداة");
					this.Onاسم_الاداةChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_العدد", DbType="Int")]
		public System.Nullable<int> العدد
		{
			get
			{
				return this._العدد;
			}
			set
			{
				if ((this._العدد != value))
				{
					this.OnالعددChanging(value);
					this.SendPropertyChanging();
					this._العدد = value;
					this.SendPropertyChanged("العدد");
					this.OnالعددChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[رقم_ الاداة]", Storage="_رقم__الاداة", DbType="NChar(10)")]
		public string رقم__الاداة
		{
			get
			{
				return this._رقم__الاداة;
			}
			set
			{
				if ((this._رقم__الاداة != value))
				{
					this.Onرقم__الاداةChanging(value);
					this.SendPropertyChanging();
					this._رقم__الاداة = value;
					this.SendPropertyChanged("رقم__الاداة");
					this.Onرقم__الاداةChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="اداة_الاعادة", Storage="_الاعادةs", ThisKey="اسم_الاداة", OtherKey="اسم_الاداة")]
		public EntitySet<الاعادة> الاعادةs
		{
			get
			{
				return this._الاعادةs;
			}
			set
			{
				this._الاعادةs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="اداة_الاستعارة", Storage="_الاستعارةs", ThisKey="اسم_الاداة", OtherKey="اسم_الاداة")]
		public EntitySet<الاستعارة> الاستعارةs
		{
			get
			{
				return this._الاستعارةs;
			}
			set
			{
				this._الاستعارةs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_الاعادةs(الاعادة entity)
		{
			this.SendPropertyChanging();
			entity.اداة = this;
		}
		
		private void detach_الاعادةs(الاعادة entity)
		{
			this.SendPropertyChanging();
			entity.اداة = null;
		}
		
		private void attach_الاستعارةs(الاستعارة entity)
		{
			this.SendPropertyChanging();
			entity.اداة = this;
		}
		
		private void detach_الاستعارةs(الاستعارة entity)
		{
			this.SendPropertyChanging();
			entity.اداة = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.الاعادة")]
	public partial class الاعادة : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.DateTime _تاريخ_الاعادة;
		
		private string _اسم_الاداة;
		
		private string _اسم_المستعير;
		
		private string _حالة_الاداة;
		
		private string _ملاحظة;
		
		private EntityRef<اداة> _اداة;
		
		private EntityRef<المستعير> _المستعير;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onتاريخ_الاعادةChanging(System.DateTime value);
    partial void Onتاريخ_الاعادةChanged();
    partial void Onاسم_الاداةChanging(string value);
    partial void Onاسم_الاداةChanged();
    partial void Onاسم_المستعيرChanging(string value);
    partial void Onاسم_المستعيرChanged();
    partial void Onحالة_الاداةChanging(string value);
    partial void Onحالة_الاداةChanged();
    partial void OnملاحظةChanging(string value);
    partial void OnملاحظةChanged();
    #endregion
		
		public الاعادة()
		{
			this._اداة = default(EntityRef<اداة>);
			this._المستعير = default(EntityRef<المستعير>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_تاريخ_الاعادة", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime تاريخ_الاعادة
		{
			get
			{
				return this._تاريخ_الاعادة;
			}
			set
			{
				if ((this._تاريخ_الاعادة != value))
				{
					this.Onتاريخ_الاعادةChanging(value);
					this.SendPropertyChanging();
					this._تاريخ_الاعادة = value;
					this.SendPropertyChanged("تاريخ_الاعادة");
					this.Onتاريخ_الاعادةChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_اسم_الاداة", DbType="NVarChar(50)")]
		public string اسم_الاداة
		{
			get
			{
				return this._اسم_الاداة;
			}
			set
			{
				if ((this._اسم_الاداة != value))
				{
					if (this._اداة.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onاسم_الاداةChanging(value);
					this.SendPropertyChanging();
					this._اسم_الاداة = value;
					this.SendPropertyChanged("اسم_الاداة");
					this.Onاسم_الاداةChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_اسم_المستعير", DbType="NVarChar(50)")]
		public string اسم_المستعير
		{
			get
			{
				return this._اسم_المستعير;
			}
			set
			{
				if ((this._اسم_المستعير != value))
				{
					if (this._المستعير.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onاسم_المستعيرChanging(value);
					this.SendPropertyChanging();
					this._اسم_المستعير = value;
					this.SendPropertyChanged("اسم_المستعير");
					this.Onاسم_المستعيرChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_حالة_الاداة", DbType="NChar(10)")]
		public string حالة_الاداة
		{
			get
			{
				return this._حالة_الاداة;
			}
			set
			{
				if ((this._حالة_الاداة != value))
				{
					this.Onحالة_الاداةChanging(value);
					this.SendPropertyChanging();
					this._حالة_الاداة = value;
					this.SendPropertyChanged("حالة_الاداة");
					this.Onحالة_الاداةChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ملاحظة", DbType="NVarChar(MAX)")]
		public string ملاحظة
		{
			get
			{
				return this._ملاحظة;
			}
			set
			{
				if ((this._ملاحظة != value))
				{
					this.OnملاحظةChanging(value);
					this.SendPropertyChanging();
					this._ملاحظة = value;
					this.SendPropertyChanged("ملاحظة");
					this.OnملاحظةChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="اداة_الاعادة", Storage="_اداة", ThisKey="اسم_الاداة", OtherKey="اسم_الاداة", IsForeignKey=true)]
		public اداة اداة
		{
			get
			{
				return this._اداة.Entity;
			}
			set
			{
				اداة previousValue = this._اداة.Entity;
				if (((previousValue != value) 
							|| (this._اداة.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._اداة.Entity = null;
						previousValue.الاعادةs.Remove(this);
					}
					this._اداة.Entity = value;
					if ((value != null))
					{
						value.الاعادةs.Add(this);
						this._اسم_الاداة = value.اسم_الاداة;
					}
					else
					{
						this._اسم_الاداة = default(string);
					}
					this.SendPropertyChanged("اداة");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="المستعير_الاعادة", Storage="_المستعير", ThisKey="اسم_المستعير", OtherKey="اسم_المستعير", IsForeignKey=true)]
		public المستعير المستعير
		{
			get
			{
				return this._المستعير.Entity;
			}
			set
			{
				المستعير previousValue = this._المستعير.Entity;
				if (((previousValue != value) 
							|| (this._المستعير.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._المستعير.Entity = null;
						previousValue.الاعادةs.Remove(this);
					}
					this._المستعير.Entity = value;
					if ((value != null))
					{
						value.الاعادةs.Add(this);
						this._اسم_المستعير = value.اسم_المستعير;
					}
					else
					{
						this._اسم_المستعير = default(string);
					}
					this.SendPropertyChanged("المستعير");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.المستعير")]
	public partial class المستعير : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _اسم_المستعير;
		
		private System.Nullable<int> _رقم_الهاتف;
		
		private string _السكن;
		
		private EntitySet<الاعادة> _الاعادةs;
		
		private EntitySet<الاستعارة> _الاستعارةs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onاسم_المستعيرChanging(string value);
    partial void Onاسم_المستعيرChanged();
    partial void Onرقم_الهاتفChanging(System.Nullable<int> value);
    partial void Onرقم_الهاتفChanged();
    partial void OnالسكنChanging(string value);
    partial void OnالسكنChanged();
    #endregion
		
		public المستعير()
		{
			this._الاعادةs = new EntitySet<الاعادة>(new Action<الاعادة>(this.attach_الاعادةs), new Action<الاعادة>(this.detach_الاعادةs));
			this._الاستعارةs = new EntitySet<الاستعارة>(new Action<الاستعارة>(this.attach_الاستعارةs), new Action<الاستعارة>(this.detach_الاستعارةs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_اسم_المستعير", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string اسم_المستعير
		{
			get
			{
				return this._اسم_المستعير;
			}
			set
			{
				if ((this._اسم_المستعير != value))
				{
					this.Onاسم_المستعيرChanging(value);
					this.SendPropertyChanging();
					this._اسم_المستعير = value;
					this.SendPropertyChanged("اسم_المستعير");
					this.Onاسم_المستعيرChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_رقم_الهاتف", DbType="Int")]
		public System.Nullable<int> رقم_الهاتف
		{
			get
			{
				return this._رقم_الهاتف;
			}
			set
			{
				if ((this._رقم_الهاتف != value))
				{
					this.Onرقم_الهاتفChanging(value);
					this.SendPropertyChanging();
					this._رقم_الهاتف = value;
					this.SendPropertyChanged("رقم_الهاتف");
					this.Onرقم_الهاتفChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_السكن", DbType="NVarChar(50)")]
		public string السكن
		{
			get
			{
				return this._السكن;
			}
			set
			{
				if ((this._السكن != value))
				{
					this.OnالسكنChanging(value);
					this.SendPropertyChanging();
					this._السكن = value;
					this.SendPropertyChanged("السكن");
					this.OnالسكنChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="المستعير_الاعادة", Storage="_الاعادةs", ThisKey="اسم_المستعير", OtherKey="اسم_المستعير")]
		public EntitySet<الاعادة> الاعادةs
		{
			get
			{
				return this._الاعادةs;
			}
			set
			{
				this._الاعادةs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="المستعير_الاستعارة", Storage="_الاستعارةs", ThisKey="اسم_المستعير", OtherKey="اسم_المستعير")]
		public EntitySet<الاستعارة> الاستعارةs
		{
			get
			{
				return this._الاستعارةs;
			}
			set
			{
				this._الاستعارةs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_الاعادةs(الاعادة entity)
		{
			this.SendPropertyChanging();
			entity.المستعير = this;
		}
		
		private void detach_الاعادةs(الاعادة entity)
		{
			this.SendPropertyChanging();
			entity.المستعير = null;
		}
		
		private void attach_الاستعارةs(الاستعارة entity)
		{
			this.SendPropertyChanging();
			entity.المستعير = this;
		}
		
		private void detach_الاستعارةs(الاستعارة entity)
		{
			this.SendPropertyChanging();
			entity.المستعير = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.الاستعارة")]
	public partial class الاستعارة : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.DateTime _تاريخ_الاستعارة;
		
		private string _اسم_الاداة;
		
		private string _اسم_المستعير;
		
		private string _اسم_المعير;
		
		private string _سبب_الاعارة;
		
		private EntityRef<اداة> _اداة;
		
		private EntityRef<المستعير> _المستعير;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onتاريخ_الاستعارةChanging(System.DateTime value);
    partial void Onتاريخ_الاستعارةChanged();
    partial void Onاسم_الاداةChanging(string value);
    partial void Onاسم_الاداةChanged();
    partial void Onاسم_المستعيرChanging(string value);
    partial void Onاسم_المستعيرChanged();
    partial void Onاسم_المعيرChanging(string value);
    partial void Onاسم_المعيرChanged();
    partial void Onسبب_الاعارةChanging(string value);
    partial void Onسبب_الاعارةChanged();
    #endregion
		
		public الاستعارة()
		{
			this._اداة = default(EntityRef<اداة>);
			this._المستعير = default(EntityRef<المستعير>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_تاريخ_الاستعارة", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime تاريخ_الاستعارة
		{
			get
			{
				return this._تاريخ_الاستعارة;
			}
			set
			{
				if ((this._تاريخ_الاستعارة != value))
				{
					this.Onتاريخ_الاستعارةChanging(value);
					this.SendPropertyChanging();
					this._تاريخ_الاستعارة = value;
					this.SendPropertyChanged("تاريخ_الاستعارة");
					this.Onتاريخ_الاستعارةChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_اسم_الاداة", DbType="NVarChar(50)")]
		public string اسم_الاداة
		{
			get
			{
				return this._اسم_الاداة;
			}
			set
			{
				if ((this._اسم_الاداة != value))
				{
					if (this._اداة.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onاسم_الاداةChanging(value);
					this.SendPropertyChanging();
					this._اسم_الاداة = value;
					this.SendPropertyChanged("اسم_الاداة");
					this.Onاسم_الاداةChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_اسم_المستعير", DbType="NVarChar(50)")]
		public string اسم_المستعير
		{
			get
			{
				return this._اسم_المستعير;
			}
			set
			{
				if ((this._اسم_المستعير != value))
				{
					if (this._المستعير.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onاسم_المستعيرChanging(value);
					this.SendPropertyChanging();
					this._اسم_المستعير = value;
					this.SendPropertyChanged("اسم_المستعير");
					this.Onاسم_المستعيرChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_اسم_المعير", DbType="NVarChar(50)")]
		public string اسم_المعير
		{
			get
			{
				return this._اسم_المعير;
			}
			set
			{
				if ((this._اسم_المعير != value))
				{
					this.Onاسم_المعيرChanging(value);
					this.SendPropertyChanging();
					this._اسم_المعير = value;
					this.SendPropertyChanged("اسم_المعير");
					this.Onاسم_المعيرChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_سبب_الاعارة", DbType="NVarChar(50)")]
		public string سبب_الاعارة
		{
			get
			{
				return this._سبب_الاعارة;
			}
			set
			{
				if ((this._سبب_الاعارة != value))
				{
					this.Onسبب_الاعارةChanging(value);
					this.SendPropertyChanging();
					this._سبب_الاعارة = value;
					this.SendPropertyChanged("سبب_الاعارة");
					this.Onسبب_الاعارةChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="اداة_الاستعارة", Storage="_اداة", ThisKey="اسم_الاداة", OtherKey="اسم_الاداة", IsForeignKey=true)]
		public اداة اداة
		{
			get
			{
				return this._اداة.Entity;
			}
			set
			{
				اداة previousValue = this._اداة.Entity;
				if (((previousValue != value) 
							|| (this._اداة.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._اداة.Entity = null;
						previousValue.الاستعارةs.Remove(this);
					}
					this._اداة.Entity = value;
					if ((value != null))
					{
						value.الاستعارةs.Add(this);
						this._اسم_الاداة = value.اسم_الاداة;
					}
					else
					{
						this._اسم_الاداة = default(string);
					}
					this.SendPropertyChanged("اداة");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="المستعير_الاستعارة", Storage="_المستعير", ThisKey="اسم_المستعير", OtherKey="اسم_المستعير", IsForeignKey=true)]
		public المستعير المستعير
		{
			get
			{
				return this._المستعير.Entity;
			}
			set
			{
				المستعير previousValue = this._المستعير.Entity;
				if (((previousValue != value) 
							|| (this._المستعير.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._المستعير.Entity = null;
						previousValue.الاستعارةs.Remove(this);
					}
					this._المستعير.Entity = value;
					if ((value != null))
					{
						value.الاستعارةs.Add(this);
						this._اسم_المستعير = value.اسم_المستعير;
					}
					else
					{
						this._اسم_المستعير = default(string);
					}
					this.SendPropertyChanged("المستعير");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
