<?xml version="1.0" encoding="utf-8"?><Database Name="haya" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-OAREN3E\ALI;Initial Catalog=haya;Integrated Security=True" SettingsObjectName="hayaaFinal.Properties.Settings" SettingsPropertyName="hayaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.اداة" Member="اداةs">
    <Type Name="اداة">
      <Column Name="اسم_الاداة" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="العدد" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[رقم_ الاداة]" Member="رقم__الاداة" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="اداة_الاعادة" Member="الاعادةs" ThisKey="اسم_الاداة" OtherKey="اسم_الاداة" Type="الاعادة" />
      <Association Name="اداة_الاستعارة" Member="الاستعارةs" ThisKey="اسم_الاداة" OtherKey="اسم_الاداة" Type="الاستعارة" />
    </Type>
  </Table>
  <Table Name="dbo.الاعادة" Member="الاعادةs">
    <Type Name="الاعادة">
      <Column Name="تاريخ_الاعادة" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="اسم_الاداة" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="اسم_المستعير" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="حالة_الاداة" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="ملاحظة" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="اداة_الاعادة" Member="اداة" ThisKey="اسم_الاداة" OtherKey="اسم_الاداة" Type="اداة" IsForeignKey="true" />
      <Association Name="المستعير_الاعادة" Member="المستعير" ThisKey="اسم_المستعير" OtherKey="اسم_المستعير" Type="المستعير" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.المستعير" Member="المستعيرs">
    <Type Name="المستعير">
      <Column Name="اسم_المستعير" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="رقم_الهاتف" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="السكن" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="المستعير_الاعادة" Member="الاعادةs" ThisKey="اسم_المستعير" OtherKey="اسم_المستعير" Type="الاعادة" />
      <Association Name="المستعير_الاستعارة" Member="الاستعارةs" ThisKey="اسم_المستعير" OtherKey="اسم_المستعير" Type="الاستعارة" />
    </Type>
  </Table>
  <Table Name="dbo.الاستعارة" Member="الاستعارةs">
    <Type Name="الاستعارة">
      <Column Name="تاريخ_الاستعارة" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="اسم_الاداة" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="اسم_المستعير" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="اسم_المعير" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="سبب_الاعارة" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="اداة_الاستعارة" Member="اداة" ThisKey="اسم_الاداة" OtherKey="اسم_الاداة" Type="اداة" IsForeignKey="true" />
      <Association Name="المستعير_الاستعارة" Member="المستعير" ThisKey="اسم_المستعير" OtherKey="اسم_المستعير" Type="المستعير" IsForeignKey="true" />
    </Type>
  </Table>
</Database>